In [2]:
import numpy as np
import pandas as pd

In [3]:
distances = pd.read_csv('data/Distances.csv', sep = ';') # ТАБЛИЦА ПОПАРНЫХ РАССТОЯНИЙ
distances=distances.rename(columns={"StCodeFrom": "operSt", "StCodeTo": "operDestSt"})
distances['operDestSt']=pd.to_numeric(distances['operDestSt'], errors='coerce')
distances['operSt']=pd.to_numeric(distances['operSt'], errors='coerce')
distances=distances.dropna(axis=0).reset_index(drop=True).astype('int64')

C:\tools\conda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [4]:
aug = pd.read_csv('data/DSL_2021_08.csv') # ПЕРЕМЕЩЕНИЕ ВАГОНОВ

In [5]:
distances

operSt  operDestSt  Distance
0             76       80410      4076
1             76       80460      2541
2             76       80570      2692
3             76       80670      2582
4             76       81190      2561
...          ...         ...       ...
35363139   25650       34750      2151
35363140   25650       34760      2145
35363141   25650       34770      2273
35363142   25650       34790      2329
35363143   25650       34800      2298

[35363144 rows x 3 columns]

In [6]:
operSt_from_dist = np.sort(distances['operSt'].unique())
operSt_from_aug = np.sort(aug['operSt'].unique())

In [25]:
unknown_operSt = np.sort(operSt_from_aug[np.isin(operSt_from_aug, operSt_from_dist)==False])
unknown_operSt

array([   85,   130,   133, ..., 97571, 97652, 98921], dtype=int64)

In [9]:
len(unknown_operSt)

1401

In [8]:
operSt_from_dist[:1000]

array([   68,    76,    84,   250,   485,   557,  1000,  1001,  1002,
        1003,  1013,  1014,  1017,  1018,  1020,  1023,  1024,  1030,
        1032,  1036,  1037,  1040,  1045,  1046,  1050,  1060,  1061,
        1066,  1068,  1069,  1070,  1076,  1080,  1084,  1090,  1095,
        1100,  1108,  1110,  1116,  1123,  1125,  1126,  1130,  1140,
        1150,  1152,  1180,  1190,  1200,  1210,  1220,  1230,  1239,
        1270,  1300,  1320,  1321,  1350,  1360,  1370,  1380,  1390,
        1400,  1410,  1430,  1440,  1445,  1460,  1470,  1480,  1490,
        1500,  1510,  1520,  1540,  1550,  1560,  1570,  1580,  1600,
        1630,  1640,  1660,  1700,  1710,  1720,  1730,  1745,  1790,
        1800,  1810,  1820,  1830,  1840,  1850,  1860,  1870,  1900,
        2000,  2010,  2020,  2030,  2040,  2050,  2052,  2060,  2070,
        2080,  2090,  2100,  2110,  2120,  2133,  2140,  2150,  2160,
        2170,  2180,  2190,  2200,  2210,  2220,  2230,  2240,  2250,
        2265,  2270,

In [10]:
#Заменяю неизвестную станцию на ближайшуюю известную
def find_nearest(value, array):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

In [23]:
aug[((aug.operSt.isin(operSt_from_aug))| (aug.operSt.isin(operSt_from_dist))|(aug.operDestSt.isin(operSt_from_aug)) |(aug.operDestSt.isin(operSt_from_dist)))& (aug.carNum==54960968)]

carNum             operDate operCode  operSt  operDestSt operCargo  \
47376    54960968  2021-08-19 15:16:00    ОТПР    87590       89540     00300   
190910   54960968  2021-08-01 17:14:00    ОТПР    83030       85160     00300   
193566   54960968  2021-08-01 02:02:00    ОТПР    79270       85160     00300   
204013   54960968  2021-08-30 07:27:00    ОТПР    92090       98610     00300   
217949   54960968  2021-08-02 16:04:00    ОТПР    85062       85160     00300   
...           ...                  ...      ...     ...         ...       ...   
5009897  54960968  2021-08-01 04:04:00    ОТПР    79210       85160     00300   
5011176  54960968  2021-08-31 15:01:00    ОТПР    93540       98610     00300   
5022241  54960968  2021-08-02 12:08:00    ОТПР    83400       85160     00300   
5037059  54960968  2021-08-02 14:21:00    ОТПР    85220       85160     00300   
5060940  54960968  2021-08-19 04:12:00    ОТПР    87290       89540     00300   

         operWeight  
47376           7.0  
190910         29.0  
193566         29.0  
204013         59.0  
217949         29.0  
...             ...  
5009897        29.0  
5011176        59.0  
5022241        29.0  
5037059        29.0  
5060940         7.0  

[314 rows x 7 columns]

In [24]:
aug[(aug.carNum==54960968)]

carNum             operDate operCode  operSt  operDestSt operCargo  \
47376    54960968  2021-08-19 15:16:00    ОТПР    87590       89540     00300   
190910   54960968  2021-08-01 17:14:00    ОТПР    83030       85160     00300   
193566   54960968  2021-08-01 02:02:00    ОТПР    79270       85160     00300   
204013   54960968  2021-08-30 07:27:00    ОТПР    92090       98610     00300   
217949   54960968  2021-08-02 16:04:00    ОТПР    85062       85160     00300   
...           ...                  ...      ...     ...         ...       ...   
5009897  54960968  2021-08-01 04:04:00    ОТПР    79210       85160     00300   
5011176  54960968  2021-08-31 15:01:00    ОТПР    93540       98610     00300   
5022241  54960968  2021-08-02 12:08:00    ОТПР    83400       85160     00300   
5037059  54960968  2021-08-02 14:21:00    ОТПР    85220       85160     00300   
5060940  54960968  2021-08-19 04:12:00    ОТПР    87290       89540     00300   

         operWeight  
47376           7.0  
190910         29.0  
193566         29.0  
204013         59.0  
217949         29.0  
...             ...  
5009897        29.0  
5011176        59.0  
5022241        29.0  
5037059        29.0  
5060940         7.0  

[314 rows x 7 columns]

# Замена станций ОТКУДА едем

In [10]:
new_operSt = []
for x in unknown_operSt:
    new_operSt.append(find_nearest(x,operSt_from_dist))

In [11]:
d = dict(zip(unknown_operSt[:500], new_operSt[:500]))
d1 = dict(zip(unknown_operSt[500:1000], new_operSt[500:1000]))
d2 = dict(zip(unknown_operSt[1000:1401], new_operSt[1000:1401]))

In [12]:
dict(zip(unknown_operSt, new_operSt)) #все замены

{85: 84,
 130: 84,
 133: 84,
 134: 84,
 135: 84,
 140: 84,
 145: 84,
 254: 250,
 337: 250,
 1021: 1020,
 1042: 1040,
 1072: 1070,
 1073: 1070,
 1082: 1080,
 1111: 1110,
 1141: 1140,
 1142: 1140,
 1151: 1150,
 1154: 1152,
 1172: 1180,
 1173: 1180,
 1174: 1180,
 1181: 1180,
 1191: 1190,
 1211: 1210,
 1231: 1230,
 1232: 1230,
 1251: 1239,
 1254: 1239,
 1261: 1270,
 1262: 1270,
 1263: 1270,
 1271: 1270,
 1272: 1270,
 1273: 1270,
 1274: 1270,
 1311: 1320,
 1312: 1320,
 1322: 1321,
 1323: 1321,
 1352: 1350,
 1371: 1370,
 1433: 1430,
 1437: 1440,
 1491: 1490,
 1612: 1600,
 1613: 1600,
 1614: 1600,
 1622: 1630,
 1623: 1630,
 1624: 1630,
 1662: 1660,
 1671: 1660,
 1674: 1660,
 1675: 1660,
 1683: 1700,
 1691: 1700,
 1692: 1700,
 1695: 1700,
 2061: 2060,
 2173: 2170,
 2175: 2170,
 2177: 2180,
 2242: 2240,
 2281: 2290,
 2292: 2290,
 2364: 2360,
 2512: 2500,
 2542: 2540,
 2543: 2540,
 2571: 2570,
 2575: 2570,
 2692: 2690,
 2701: 2700,
 2752: 2750,
 2761: 2760,
 2771: 2770,
 2773: 2770,
 2774: 2770,

In [27]:
s={1021: 1020,
 1042: 1040,
 1072: 1070,
 1073: 1070,
 1082: 1080,
 1111: 1110,
 1141: 1140,
 1142: 1140,
 1151: 1150,
 1154: 1152,
 1172: 1180,
 1173: 1180,
 1174: 1180,
 1181: 1180,
 1191: 1190,
 1211: 1210,
 1231: 1230,
 1232: 1230,
 1251: 1239,
 1254: 1239,
 1261: 1270}
s

{1021: 1020,
 1042: 1040,
 1072: 1070,
 1073: 1070,
 1082: 1080,
 1111: 1110,
 1141: 1140,
 1142: 1140,
 1151: 1150,
 1154: 1152,
 1172: 1180,
 1173: 1180,
 1174: 1180,
 1181: 1180,
 1191: 1190,
 1211: 1210,
 1231: 1230,
 1232: 1230,
 1251: 1239,
 1254: 1239,
 1261: 1270}

In [13]:
#Если считать что станции означают километры, то посомтрю на сколько максимально изменилась станция
#если очень сильно, то будет плохо
dstack=np.dstack((unknown_operSt,new_operSt))
np.sort(dstack[0][:,0]-dstack[0][:,1])

array([-219,  -50,  -43, ...,   56,   61,   87], dtype=int64)

In [14]:
#Плоховато получилось со станциямм где отличается на 30 и более. Надо подумать, что делать!

In [15]:
aug['operSt']=aug['operSt'].replace(d)
aug['operSt']=aug['operSt'].replace(d1)
aug['operSt']=aug['operSt'].replace(d1)

In [16]:
aug['operSt']

0             84
1             84
2             84
3             84
4             84
           ...  
5061929    96342
5061930    96342
5061931    96342
5061932    96342
5061933    96342
Name: operSt, Length: 5061934, dtype: int64

In [17]:
aug.to_csv('new_aug.csv')

# Замена станций КУДА едем

In [18]:
#то же самое попробую сделать со станциями куда едем

In [19]:
destSt_from_dist = np.sort(distances['operDestSt'].unique())
destSt_from_aug = np.sort(aug['operSt'].unique())

In [20]:
unknown_destSt = np.sort(destSt_from_aug[np.isin(destSt_from_aug, destSt_from_dist)==False])

In [21]:
len(unknown_destSt)

863

In [22]:
#слишком много не совпадений

In [23]:
# пусть есть станции А-B-C-D
#будем считать расстояние B-C как (B-D) - (C-D)

In [24]:
destSt_from_dist = np.sort(distances['operDestSt'].unique())
destSt_from_aug = np.sort(aug['operDestSt'].unique())

In [25]:
unknown_destSt = np.sort(destSt_from_aug[np.isin(destSt_from_aug, destSt_from_dist)==False])

In [26]:
unknown_destSt

array([  485,  1095, 13094, 13660, 36170, 38550, 66300, 75640, 87720],
      dtype=int64)

In [27]:
np.sort(destSt_from_dist)[:1000]

array([   68,  1000,  1001,  1014,  1017,  1020,  1023,  1024,  1030,
        1036,  1037,  1040,  1050,  1060,  1061,  1066,  1068,  1070,
        1076,  1080,  1084,  1090,  1100,  1108,  1110,  1126,  1130,
        1140,  1150,  1152,  1180,  1190,  1200,  1210,  1220,  1230,
        1239,  1270,  1300,  1320,  1321,  1350,  1360,  1370,  1380,
        1390,  1400,  1410,  1430,  1440,  1460,  1470,  1480,  1490,
        1500,  1510,  1520,  1540,  1550,  1560,  1570,  1580,  1600,
        1630,  1640,  1660,  1700,  1710,  1720,  1730,  1790,  1800,
        1810,  1820,  1830,  1840,  1850,  1860,  1870,  1900,  2000,
        2010,  2020,  2030,  2040,  2050,  2060,  2070,  2080,  2090,
        2100,  2110,  2120,  2140,  2150,  2160,  2170,  2180,  2190,
        2200,  2210,  2220,  2230,  2240,  2250,  2270,  2290,  2300,
        2310,  2320,  2360,  2370,  2380,  2390,  2400,  2410,  2420,
        2440,  2450,  2460,  2470,  2480,  2490,  2500,  2530,  2540,
        2550,  2560,

In [28]:
new_destSt = []
for x in unknown_destSt:
    new_destSt.append(find_nearest(x,destSt_from_dist))

In [29]:
d = dict(zip(unknown_destSt, new_destSt))
d

{485: 68,
 1095: 1090,
 13094: 13120,
 13660: 13670,
 36170: 36160,
 38550: 38540,
 66300: 66302,
 75640: 75630,
 87720: 87730}

In [30]:
aug['operDestSt']=aug['operDestSt'].replace(d)

In [31]:
aug.to_csv('new_aug2.csv')

In [32]:
#Посмотрю  сколько нанов

In [33]:
aug1=aug.drop_duplicates()
aug1=aug1[aug1["operCode"].isin(['ПРИБ ','ОТПР ','РМНТ '])]
sort_aug=aug1.sort_values(by=['operDate'])
all_carNum=sort_aug['carNum'].unique()
all_movement_for_carriage =sort_aug[sort_aug['carNum']==all_carNum[0]].reset_index(drop=True)